### ISSUE TITLE
QUESTION: is that batch correct?

### ISSUE THREAD

**Issue by Benman2785** [FlyGoat/RyzenAdj#11]
hey, do i need more to add to the batch?
i mean - is VRM Current adjust needed?

> @echo off
> cd %~dp0
> ryzenadj.exe --stapm-limit=25000 --fast-limit=25000 --slow-limit=25000 --tctl-temp=75 --vrmmax-current=50000
> cls
> echo MSGBOX "APU runs now with 25W TDP" > %temp%\25Wmsgbox.vbs
> call %temp%\25Wmsgbox.vbs
> del %temp%\25Wmsgbox.vbs /f /q
> exit

**Comment by GoelBiju** [comment]
@Benman2785 you shouldn't need to change anything further than these settings to notice an improvement in your system. You can also use the RyzenAdj GUI to make it easier to change these settings rather than using a batch file.

You can find the GUI under releases: https://github.com/FlyGoat/RyzenAdj/releases
